In [2]:
import torch

torch.tensor([1.2, 3.4]).dtype

torch.float32

In [3]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float64

In [4]:
a = torch.tensor([1.2, 3.4])
print("a.dtype:", a.dtype)
print("a.long()方法：", a.long().dtype)
print("a.int()方法：", a.int().dtype)
print("a.float()方法：", a.float().dtype)

a.dtype: torch.float64
a.long()方法： torch.int64
a.int()方法： torch.int32
a.float()方法： torch.float32


In [5]:
torch.set_default_tensor_type(torch.FloatTensor)  #恢复数据类型
torch.tensor([1.2, 3.4]).dtype

torch.float32

In [6]:
torch.get_default_dtype()  #获取默认数据类型

torch.float32

In [7]:
#生成tensor
a = torch.tensor([[1.2, 1.3], [3.4, 3.5]])
a

tensor([[1.2000, 1.3000],
        [3.4000, 3.5000]])

In [8]:
a.shape

torch.Size([2, 2])

In [9]:
a.size()

torch.Size([2, 2])

In [10]:
a.numel()

4

In [11]:
b = torch.tensor((1, 2, 3, 4), dtype=torch.float32, requires_grad=True)  #设置张量有梯度，只有浮点型才能计算梯度
b

tensor([1., 2., 3., 4.], requires_grad=True)

In [12]:
y = b.pow(2).sum()
y.backward()
b.grad

tensor([2., 4., 6., 8.])

In [13]:
#使用torch.Tensor()函数创建张量
c = torch.Tensor([1, 2, 3, 4])
c

tensor([1., 2., 3., 4.])

In [14]:
d = torch.Tensor(2, 3)
d,

(tensor([[1.3237e+22, 6.6820e+22, 2.0682e+20],
         [2.6368e-09, 4.1915e+21, 1.6778e+22]]),)

In [15]:
#torch.ones_like() torch.zero() torch.rand()函数
e = torch.ones_like(d)
f = torch.zeros_like(d)
g = torch.rand_like(d)
print(e, f, g)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[0.1795, 0.9908, 0.0848],
        [0.6829, 0.6210, 0.4237]])


In [16]:
#d.new_**()类函数
h = d.new_tensor(d)
h

C:\Users\User\AppData\Local\Temp\ipykernel_17356\1493618824.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  h=d.new_tensor(d)


tensor([[1.3237e+22, 6.6820e+22, 2.0682e+20],
        [2.6368e-09, 4.1915e+21, 1.6778e+22]])

In [17]:
#张量与numpy转化
import numpy as np

i = np.ones((3, 4))
iTensor = torch.as_tensor(i)
iTensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [18]:
iTensor = torch.from_numpy(i)
iTensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [19]:
torch.manual_seed(123)
a = torch.normal(mean=0.0, std=torch.tensor(1.0))
a

tensor(-0.1115)

In [20]:
torch.manual_seed(123)
a = torch.normal(mean=0.0, std=torch.arange(1, 5.0))
a

tensor([-0.1115,  0.2407, -1.1089, -0.9617])

In [21]:
torch.manual_seed(123)
a = torch.rand(3, 4)
a

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

In [22]:
torch.manual_seed(123)
c = torch.ones(2, 3)
print(c)
d = torch.rand_like(c)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])


In [23]:
print(torch.randn(3, 3))
print(torch.randn_like(c))

tensor([[ 0.9447,  0.6217, -1.3501],
        [-0.1881, -2.3891, -0.4759],
        [ 1.7603,  0.6547,  0.5490]])
tensor([[ 0.3671,  0.1219,  0.6466],
        [-1.4168,  0.8429, -0.6307]])


In [24]:
torch.manual_seed(123)
torch.randperm(10)

tensor([2, 0, 8, 1, 3, 7, 4, 9, 5, 6])

In [25]:
##使用torch.arange()生成张量
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [26]:
torch.linspace(start=1, end=10, steps=5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [27]:
torch.logspace(start=0.1, end=1.0, steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [28]:
##使用tensor.reshape()方法设置张量的形状大小
a = torch.arange(12.0).reshape(3, 4)
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
torch.reshape(input=a, shape=(2, -1))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [30]:
##使用resize_()方法
a.resize_(2, 6)
a

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [31]:
b = torch.arange(10.0, 19.0).reshape(3, 3)
a.resize_as_(b)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [32]:
b

tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [33]:
##torch.unsqueeze()函数在指定维度插入尺寸为1的新张量
a = torch.arange(12.0).reshape(2, 6)
print(a.shape)
b = torch.unsqueeze(a, dim=0)
b.shape

torch.Size([2, 6])


torch.Size([1, 2, 6])

In [34]:
##torch.squeeze()移除所有维度为1的维度
c = b.unsqueeze(dim=3)
print("c.shape:", c.shape)
d = torch.squeeze(c)
print("d.shape:", d.shape)

c.shape: torch.Size([1, 2, 6, 1])
d.shape: torch.Size([2, 6])


In [35]:
##起初指定维度为1的维度
e = torch.squeeze(c, dim=3)
print("e.shape", e.shape)

e.shape torch.Size([1, 2, 6])


In [36]:
##使用.repeat()方法拓展张量
d = b.repeat(1, 2, 2)
print(d)
print(d.shape)

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.,  6.,  7.,  8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.,  6.,  7.,  8.,  9., 10., 11.]]])
torch.Size([1, 4, 12])


In [37]:
##利用切片和索引获取张量中的元素
a = torch.arange(12).reshape(1, 3, 4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [38]:
a[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [39]:
##获取第0维度下的矩阵的前两行元素
a[0, 0:2, :]

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [40]:
##获取第0维度下的矩阵，最后一行-4,-1lie
a[0, -1, -4:-1]

tensor([ 8,  9, 10])

In [41]:
##根据条件筛选
b = -a
torch.where(a > 5, a, b)

tensor([[[ 0, -1, -2, -3],
         [-4, -5,  6,  7],
         [ 8,  9, 10, 11]]])

In [42]:
##获取a中大于5的元素
a[a > 5]

tensor([ 6,  7,  8,  9, 10, 11])

In [43]:
##获取矩阵张量的下三角部分
torch.tril(a, diagonal=0, )

tensor([[[ 0,  0,  0,  0],
         [ 4,  5,  0,  0],
         [ 8,  9, 10,  0]]])

In [44]:
torch.triu(a, diagonal=1)

tensor([[[ 0,  1,  2,  3],
         [ 0,  0,  6,  7],
         [ 0,  0,  0, 11]]])

In [45]:
##diagonal参数控制要考虑的对角线
torch.tril(a, diagonal=1, )

tensor([[[ 0,  1,  0,  0],
         [ 4,  5,  6,  0],
         [ 8,  9, 10, 11]]])

In [46]:
##获取矩阵张量的对角线元素，input需要是一个二维张量
c = a.reshape(3, 4)
print(c)
print(torch.diag(c, diagonal=0))
print(torch.diag(c, diagonal=1))


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  5, 10])
tensor([ 1,  6, 11])


In [47]:
##提供对角线元素生成矩阵张量
torch.diag(torch.tensor([1, 2, 3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [48]:
a = torch.arange(6.0).reshape(2, 3)
b = torch.linspace(0, 10, 6).reshape(2, 3)
c = torch.cat((a, b), dim=0)
c

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [49]:
##在1维度连接张量
d = torch.cat((a, b), dim=1)
d

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])

In [50]:
e = torch.cat((a[:, 0:2], a, b), dim=1)
e

tensor([[ 0.,  1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  3.,  4.,  5.,  6.,  8., 10.]])

In [51]:
##在1维度链接3个张量
e = torch.cat((a[:, 1:2], a, b), dim=1)
e

tensor([[ 1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  3.,  4.,  5.,  6.,  8., 10.]])

In [52]:
f = torch.stack((a, b), dim=0)
print(f)
print(f.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]])
torch.Size([2, 2, 3])


In [53]:
g = torch.stack((a, b), dim=2)
print(g)
print(g.shape)

tensor([[[ 0.,  0.],
         [ 1.,  2.],
         [ 2.,  4.]],

        [[ 3.,  6.],
         [ 4.,  8.],
         [ 5., 10.]]])
torch.Size([2, 3, 2])


In [54]:
##在行上将张量e分为两块
torch.chunk(e, 2, dim=0)

(tensor([[1., 0., 1., 2., 0., 2., 4.]]),
 tensor([[ 4.,  3.,  4.,  5.,  6.,  8., 10.]]))

In [55]:
d1, d2 = torch.chunk(d, 2, dim=1)
print(d1)
print(d2)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


In [56]:
##如果沿给定维度dim的张量大小不
e1, e2, e3 = torch.chunk(e, 3, dim=1)
print(e)
print(e1)
print(e2)
print(e3)

tensor([[ 1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  3.,  4.,  5.,  6.,  8., 10.]])
tensor([[1., 0., 1.],
        [4., 3., 4.]])
tensor([[2., 0., 2.],
        [5., 6., 8.]])
tensor([[ 4.],
        [10.]])


In [57]:
d1, d2, d3 = torch.split(d, [1, 2, 3], dim=1)
print(d)
print(d1)
print(d2)
print(d3)

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])
tensor([[0.],
        [3.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


In [65]:
##比较两个数是否相近
a = torch.tensor([10.0])
b = torch.tensor([10.1])
print(torch.allclose(a, b, rtol=5.0, atol=8.0, equal_nan=False))
print(torch.allclose(a, b, rtol=0.1, atol=0.01, equal_nan=False))

True
True


In [66]:
##如果equal_nan=True,那么缺失值可以判断接近
a = torch.tensor(float("nan"))
print(torch.allclose(a, a, equal_nan=False))
print(torch.allclose(a, a, equal_nan=True))

False
True


In [69]:
##计算元素是否相等
a = torch.tensor([1, 2, 3, 4, 5, 6])
b = torch.arange(1, 7)
c = torch.unsqueeze(b, dim=0)
print(torch.eq(a, b))
print(torch.eq(a, c))
##判断两个张量是否具有相同的形状和元素
print(torch.equal(a, b))
print(torch.equal(a, c))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])
True
False


In [73]:
##逐元素比较大于等于
print(torch.ge(a, b))
print(torch.ge(a, c))
##逐元素比较大于
print(torch.gt(a, b))
print(torch.gt(a, c))
##逐元素比较小于等于
print(torch.le(a, b))
print(torch.le(a, c))
##逐元素比较不等于
print(torch.ne(a, b))
print(torch.ne(a, c))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])
tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])
tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])
tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [74]:
##矩阵逐元素相乘
a = torch.arange(6.0).reshape(2, 3)
b = torch.linspace(10, 20, steps=6).reshape(2, 3)
print("a:", a)
print("b:", b)
print(a * b)
##逐元素相除
print(a / b)

a: tensor([[0., 1., 2.],
        [3., 4., 5.]])
b: tensor([[10., 12., 14.],
        [16., 18., 20.]])
tensor([[  0.,  12.,  28.],
        [ 48.,  72., 100.]])
tensor([[0.0000, 0.0833, 0.1429],
        [0.1875, 0.2222, 0.2500]])


In [75]:
##逐元素相加
print(a + b)
##逐元素相减
print(a - b)
##逐元素整除
print(b // a)

tensor([[10., 13., 16.],
        [19., 22., 25.]])
tensor([[-10., -11., -12.],
        [-13., -14., -15.]])
tensor([[inf, 12.,  7.],
        [ 5.,  4.,  4.]])


In [77]:
##张量的幂
print(torch.pow(a, 3))
print(a ** 3)

tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])
tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])


In [79]:
##计算张量的指数
print(torch.exp(a))
##计算张量的对数
print(torch.log(a))
##计算张量的平方根
print(torch.sqrt(a))
print(a ** 0.5)
##计算张量平方根倒数
print(torch.rsqrt(a))
print(1 / (a ** 0.5))

tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])
tensor([[  -inf, 0.0000, 0.6931],
        [1.0986, 1.3863, 1.6094]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])


In [81]:
##根据最大值裁剪
print(torch.clamp_max(a, 4))
##根据最小值裁剪
print(torch.clamp_min(a, 3))
##根据范围裁剪
print(torch.clamp(a, 2.5, 4))

tensor([[0., 1., 2.],
        [3., 4., 4.]])
tensor([[3., 3., 3.],
        [3., 4., 5.]])
tensor([[2.5000, 2.5000, 2.5000],
        [3.0000, 4.0000, 4.0000]])


In [82]:
##矩阵的转置
c=torch.t(a)
print(c)
##矩阵运算,矩阵相乘,a的行数要等于c的列数
print(a.matmul(c))
a=torch.arange(12.0).reshape(2,2,3)
b=torch.arange(12.0).reshape(2,3,2)
ab=torch.matmul(a,b)
print(ab)

tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])
tensor([[ 5., 14.],
        [14., 50.]])
tensor([[[ 10.,  13.],
         [ 28.,  40.]],

        [[172., 193.],
         [244., 274.]]])


In [83]:
##矩阵相乘只计算最后面两个维度的乘法
print(ab[0].eq(torch.matmul(a[0],b[0])))
print(ab[1].eq(torch.matmul(a[1],b[1])))

tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])


In [85]:
##计算矩阵的逆
c=torch.rand(3,3)
d=torch.inverse(c)
torch.mm(c,d)

tensor([[1.0000e+00, 0.0000e+00, 2.3842e-07],
        [0.0000e+00, 1.0000e+00, 2.3842e-07],
        [0.0000e+00, 2.3842e-07, 1.0000e+00]])

In [86]:
##计算张量矩阵的迹，对角线元素的和
torch.trace(torch.arange(9.0).reshape(3,3))

tensor(12.)

In [87]:
##一维张量的最大值和最小值
a=torch.tensor([12.,34,25,11,67,32,29,30,99,55,23,44])
##最大值及位置
print("最大值：",a.max())
print("最大值位置：",a.argmax())
##最小值及位置
print("最小值:",a.min())
print("最小值位置：",a.argmin())

最大值： tensor(99.)
最大值位置： tensor(8)
最小值: tensor(11.)
最小值位置： tensor(3)


In [89]:
##二维张量的最大值和最小值
b=a.reshape(3,4)
print("2-d张量b:\n",b)
##最大值及位置（每行）
print("最大值:\n",b.max(dim=1))
print("最大值位置：",b.argmax(dim=1))
##最小值及位置（每行）
print("最小值:\n",b.min(dim=0))
print("最小值位置：",b.argmin(dim=0))

2-d张量b:
 tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
最大值:
 torch.return_types.max(
values=tensor([34., 67., 99.]),
indices=tensor([1, 0, 0]))
最大值位置： tensor([1, 0, 0])
最小值:
 torch.return_types.min(
values=tensor([12., 32., 23., 11.]),
indices=tensor([0, 1, 2, 0]))
最小值位置： tensor([0, 1, 2, 0])


In [92]:
##张量排序,分别输出从小到大的结果和相应的元素在原始位置的索引
print(torch.sort(a))
##降序排列
print(torch.sort(a, descending=True))

torch.return_types.sort(
values=tensor([99., 67., 55., 44., 34., 32., 30., 29., 25., 23., 12., 11.]),
indices=tensor([ 8,  4,  9, 11,  1,  5,  7,  6,  2, 10,  0,  3]))

In [93]:
##对2-d张量进行排序
bsort,bsort_id=torch.sort(b)
print("b sort:\n",bsort)
print("b sort index:\n",bsort_id)
print("b argsort:\n",torch.argsort(b))


b sort:
 tensor([[11., 12., 25., 34.],
        [29., 30., 32., 67.],
        [23., 44., 55., 99.]])
b sort index:
 tensor([[3, 0, 2, 1],
        [2, 3, 1, 0],
        [2, 3, 1, 0]])
b argsort:
 tensor([[3, 0, 2, 1],
        [2, 3, 1, 0],
        [2, 3, 1, 0]])


In [94]:
##获取张量前几个最大的数值
print(torch.topk(a, 4))
##获取2d张量每列前几个最大的数值
btop2,btop2_id=torch.topk(b,2,dim=0)
print("b 每列 top2:\n",btop2)
print("b 每列 top2 位置:\n",btop2_id)

torch.return_types.topk(
values=tensor([99., 67., 55., 44.]),
indices=tensor([ 8,  4,  9, 11]))
b 每列 top2:
 tensor([[99., 55., 29., 44.],
        [67., 34., 25., 30.]])
b 每列 top2 位置:
 tensor([[2, 2, 1, 2],
        [1, 0, 0, 1]])


In [95]:
##获取张量第k小的数值的位置
torch.kthvalue(a,3)

torch.return_types.kthvalue(
values=tensor(23.),
indices=tensor(10))

In [96]:
##获取2d张量第k小的数值和位置
bkth,bkth_id=torch.kthvalue(b,3,dim=1,keepdim=True)
bkth

tensor([[25.],
        [32.],
        [55.]])

In [98]:
##平均值，计算每行的平均值
print(torch.mean(b,dim=1,keepdim=True))
print(torch.mean(b, dim=0, keepdim=True))

tensor([[20.5000],
        [39.5000],
        [55.2500]])
tensor([[59.3333, 40.3333, 25.6667, 28.3333]])


In [99]:
##计算每行和
print(torch.sum(b,dim=1,keepdim=True))
##计算每列的和
print(torch.sum(b,dim=0,keepdim=True))
##按行计算累加和
print(torch.cumsum(b, dim=1))
##按列计算累加和
print(torch.cumsum(b,dim=0))

tensor([[ 82.],
        [158.],
        [221.]])
tensor([[178., 121.,  77.,  85.]])
tensor([[ 12.,  46.,  71.,  82.],
        [ 67.,  99., 128., 158.],
        [ 99., 154., 177., 221.]])
tensor([[ 12.,  34.,  25.,  11.],
        [ 79.,  66.,  54.,  41.],
        [178., 121.,  77.,  85.]])


In [102]:
##计算每行中位数
print(torch.median(b, dim=1, keepdim=True))
##计算每列的中位数
print(torch.median(b,dim=0,keepdim=True))

torch.return_types.median(
values=tensor([[12.],
        [30.],
        [44.]]),
indices=tensor([[0],
        [3],
        [3]]))
torch.return_types.median(
values=tensor([[67., 34., 25., 30.]]),
indices=tensor([[1, 0, 0, 1]]))


In [104]:
##按行计算成积
print(torch.prod(b,dim=1,keepdim=True))
##按照列计算乘积
print(torch.prod(b, dim=0, keepdim=True))

tensor([[ 112200.],
        [1865280.],
        [5510340.]])
tensor([[79596., 59840., 16675., 14520.]])


In [105]:
##标准差
torch.std(a)

tensor(25.0108)

In [2]:
import torch
a=torch.tensor([1.2, 3.4])
print(a!=1.2)

tensor([False,  True])
